### ISSUE TITLE
ec2_eip fails when trying to allocate a new elastic IP and associate it with an instance in af-south-1 (cape town)

### ISSUE THREAD

**Issue by itaylaufer** [ansible-collections/community.aws#274]
##### SUMMARY
I created an instance in af-south-1 with ec2_instance module. 
After that i try to allocate a new elastic ip and associate it with the instance but it fails

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ec2_eip module
##### ANSIBLE VERSION

```paste below
ansible 2.9.10
  config file = ~/aws/ansible-aws/ansible.cfg
  configured module search path = [~/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location =~/Library/Python/3.7/lib/python/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.6 (default, Dec 30 2019, 19:38:28) [Clang 11.0.0 (clang-1100.0.33.16)]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

macOS Cataling
Centos7

##### STEPS TO REPRODUCE

create an instance if af-south-1 (capetown) region and run this simple task:

```yaml
    - name: allocate a new elastic IP and associate it with an instance
      ec2_eip:
        device_id: "<the instance id you created before>"
        region: "af-south-1"
```

##### EXPECTED RESULTS

An elastic eip would be created and associated with an instance.

##### ACTUAL RESULTS

The playbook fails with this error:

```paste below
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'NoneType' object has no attribute 'split'
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1603293420.8169715-1031-51070565170671/AnsiballZ_ec2_eip.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1603293420.8169715-1031-51070565170671/AnsiballZ_ec2_eip.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1603293420.8169715-1031-51070565170671/AnsiballZ_ec2_eip.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.cloud.amazon.ec2_eip', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/local/lib/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/local/lib/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/local/lib/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_ec2_eip_payload_z_m5p1gn/ansible_ec2_eip_payload.zip/ansible/modules/cloud/amazon/ec2_eip.py\", line 570, in <module>\n  File \"/tmp/ansible_ec2_eip_payload_z_m5p1gn/ansible_ec2_eip_payload.zip/ansible/modules/cloud/amazon/ec2_eip.py\", line 533, in main\n  File \"/tmp/ansible_ec2_eip_payload_z_m5p1gn/ansible_ec2_eip_payload.zip/ansible/modules/cloud/amazon/ec2_eip.py\", line 307, in find_address\n  File \"/tmp/ansible_ec2_eip_payload_z_m5p1gn/ansible_ec2_eip_payload.zip/ansible/modules/cloud/amazon/ec2_eip.py\", line 295, in _find_address_by_device_id\n  File \"/usr/local/lib/python3.6/site-packages/boto/ec2/connection.py\", line 1811, in get_all_addresses\n    return self.get_list('DescribeAddresses', params, [('item', Address)], verb='POST')\n  File \"/usr/local/lib/python3.6/site-packages/boto/connection.py\", line 1170, in get_list\n    response = self.make_request(action, params, path, verb)\n  File \"/usr/local/lib/python3.6/site-packages/boto/connection.py\", line 1116, in make_request\n    return self._mexe(http_request)\n  File \"/usr/local/lib/python3.6/site-packages/boto/connection.py\", line 927, in _mexe\n    request.authorize(connection=self)\n  File \"/usr/local/lib/python3.6/site-packages/boto/connection.py\", line 377, in authorize\n    connection._auth_handler.add_auth(self, **kwargs)\n  File \"/usr/local/lib/python3.6/site-packages/boto/auth.py\", line 574, in add_auth\n    string_to_sign = self.string_to_sign(req, canonical_request)\n  File \"/usr/local/lib/python3.6/site-packages/boto/auth.py\", line 514, in string_to_sign\n    sts.append(self.credential_scope(http_request))\n  File \"/usr/local/lib/python3.6/site-packages/boto/auth.py\", line 496, in credential_scope\n    region_name = self.determine_region_name(http_request.host)\n  File \"/usr/local/lib/python3.6/site-packages/boto/auth.py\", line 465, in determine_region_name\n    parts = self.split_host_parts(host)\n  File \"/usr/local/lib/python3.6/site-packages/boto/auth.py\", line 462, in split_host_parts\n    return host.split('.')\nAttributeError: 'NoneType' object has no attribute 'split'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```

**Comment by tremble** [comment]
The version of ec2_eip that ships with Ansible 2.9 is, unfortunately, still based on the boto v2 library.  The Cape Town region is very new and as such unsupported by boto v2.

The version of ec2_eip that ships with Ansible 2.10 is based on boto3 and should work with the Cape Town region.  Please try either the version available in Ansible 2.10, or the version in this collection.

Due to the very significant changes back end changes that migrating to boto3 results in we're not planning on backporthing this to Ansible 2.9 at this time.

**Comment by itaylaufer** [comment]
Hi @tremble , Thanks for you help!
It does work with ansible 2.10.

If i have exactly the same question (and error) about `ec2_vpc_route_table_facts` should i open a new issue?

Also, is there any central place stating which modules work or don't work with Cape Town?

**Comment by tremble** [comment]
I'm not aware of such a list, at a quick glance the following are our boto v2 modules and likely won't work with Cape Town:

- ec2_elb_lb
- ec2
- ec2_snapshot
- ec2_vol
- ec2_vpc_dhcp_option
- dynamodb_table
- ecs_ecr
- ec2_elb
- ec2_elb_info
- ec2_vpc_route_table_info
- elasticache_subnet_group
- elb_classic_lb
- elb_instance
- iam
- iam_cert
- rds
- redshift_subnet_group
- route53
- route53_health_check
- route53_info
- s3_logging
- s3_sync

It looks like we do at least have integration tests for ec2_vpc_route_table_info so migration shouldn't be too painful.  It's tracked on our project board, and I've converted it to an issue (#277) but we can't make any guarantees when it'll be available.

In theory all other modules are boto3 based and *should* work...
