### PR TITLE
ecs_taskdefinition: ensure cast to integer and idempotency fix

### PR DESCRIPTION
**Pull request by alinabuzachis**
##### SUMMARY

ecs_taskdefinition: Ensure cast to integer and fix taskdefinition creation idempotency.
Fixes: https://github.com/ansible-collections/community.aws/issues/570

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

ecs_taskdefinition

### CODE REVIEW

**Comment by alinabuzachis** [comment]
> I get an error with this branch when using `maxSwap` and `swappiness`:
> 
> ```
> File \"/tmp/ansible_ecs_taskdefinition_payload_tdgmg8iq/ansible_ecs_taskdefinition_payload.zip/ansible/modules/ecs_taskdefinition.py\", line 832, in main\nTypeError: '<' not supported between instances of 'str' and 'int'\n",
> ```
> 
> Adding some casts fixes it. Not sure if it would be better to do inline or ensure that container has the ints.
> 
> ```
> diff --git a/plugins/modules/ecs_taskdefinition.py b/plugins/modules/ecs_taskdefinition.py
> index 577b0ed..c6e488b 100644
> --- a/plugins/modules/ecs_taskdefinition.py
> +++ b/plugins/modules/ecs_taskdefinition.py
> @@ -829,12 +829,12 @@ def main():
>  
>                  if linux_param == 'maxSwap' and launch_type == 'FARGATE':
>                      module.fail_json(msg='maxSwap parameter is not supported with the FARGATE launch type.')
> -                elif linux_param == 'maxSwap' and container['linuxParameters']['maxSwap'] < 0:
> +                elif linux_param == 'maxSwap' and int(container['linuxParameters']['maxSwap']) < 0:
>                      module.fail_json(msg='Accepted values for maxSwap are 0 or any positive integer.')
>  
>                  if (
>                      linux_param == 'swappiness' and
> -                    (container['linuxParameters']['swappiness'] < 0 or container['linuxParameters']['swappiness'] > 100)
> +                    (int(container['linuxParameters']['swappiness']) < 0 or int(container['linuxParameters']['swappiness']) > 100)
>                  ):
>                      module.fail_json(msg='Accepted values for swappiness are whole numbers between 0 and 100.')
> ```

Oh, that's true. It's missing the cast to int there. I'll fix it right now. Thank you for trying it and letting me know. Can you try again please? Thanks.

**Comment by amackenz2048** [comment]
That works for me!

File: plugins/modules/ecs_taskdefinition.py [hunk 1]
```diff
@@ -682,6 +686,23 @@ def register_task(self, family, task_role_arn, execution_role_arn, network_mode,
...
+            if 'linuxParameters' in container:
+                for linux_param in container.get('linuxParameters'):
+                    if linux_param == 'tmpfs':
+                        for tmpfs_param in container['linuxParameters']['tmpfs']:
+                            if 'size' in tmpfs_param:
+                                tmpfs_param['size'] = int(tmpfs_param['size'])
+
+                    for param in ('maxSwap', 'swappiness', 'sharedMemorySize'):
+                        if param in linux_param:
+                            container['linuxParameters'][param] = int(container['linuxParameters'][param])
```
Comment (markuman) [inline plugins/modules/ecs_taskdefinition.py:698]:
```suggestion
                    if linux_param in ('maxSwap', 'swappiness', 'sharedMemorySize'):`
                        container['linuxParameters'][param] = int(container['linuxParameters'][param])
```

File: plugins/modules/ecs_taskdefinition.py [hunk 2]
```diff
@@ -682,6 +686,23 @@ def register_task(self, family, task_role_arn, execution_role_arn, network_mode,
...
+
+            if 'ulimits' in container:
+                for limits_mapping in container['ulimits']:
+                    for limit in ('softLimit', 'hardLimit'):
+                        if limit in limits_mapping:
+                            limits_mapping[limit] = int(limits_mapping[limit])
```
Comment (markuman) [inline plugins/modules/ecs_taskdefinition.py:704]:
```suggestion
                for limits_mapping in container['ulimits']:
                    for limit in ('softLimit', 'hardLimit'):
                        if limit == limits_mapping:
                            limits_mapping[limit] = int(limits_mapping[limit])
```

File: plugins/modules/ecs_taskdefinition.py [hunk 3]
```diff
@@ -796,28 +817,31 @@ def main():
...
             for linux_param in container.get('linuxParameters', {}):
-                if linux_param.get('devices') and launch_type == 'FARGATE':
+                if linux_param == 'maxSwap' and launch_type == 'FARGATE':
                     module.fail_json(msg='devices parameter is not supported with the FARGATE launch type.')
 
-                if linux_param.get('maxSwap') and launch_type == 'FARGATE':
+                if linux_param == 'maxSwap' and launch_type == 'FARGATE':
                     module.fail_json(msg='maxSwap parameter is not supported with the FARGATE launch type.')
-                elif linux_param.get('maxSwap') and linux_param['maxSwap'] < 0:
+                elif linux_param == 'maxSwap' and int(container['linuxParameters']['maxSwap']) < 0:
```
Comment (markuman) [inline plugins/modules/ecs_taskdefinition.py:832]: What happen if key `maxSwap` does not exist? Is it possible? I've no idea.

Comment (markuman) [reply plugins/modules/ecs_taskdefinition.py:832]: same for `swappiness`

**Review by markuman — CHANGES_REQUESTED** [review]
Some nits, otherwise looks good to me.

File: plugins/modules/ecs_taskdefinition.py (hunk 1 above)
Comment (alinabuzachis) [reply plugins/modules/ecs_taskdefinition.py:698]: @markuman Thank you for reviewing. I used the for loop here because I need to cast to int all these parameters `('maxSwap', 'swappiness', 'sharedMemorySize')`. The user can use all together.

File: plugins/modules/ecs_taskdefinition.py (hunk 2 above)
Comment (alinabuzachis) [reply plugins/modules/ecs_taskdefinition.py:704]: @markuman `limits_mapping` is a dict, for this reason I used `if limit in limits_mapping`.

File: plugins/modules/ecs_taskdefinition.py (hunk 3 above)
Comment (alinabuzachis) [reply plugins/modules/ecs_taskdefinition.py:832]: @markuman `maxSwap` and `swappiness` are optional and they can be specified within `linuxParameters`. If this is what you meant. This flow here is only executed when the parameters are specified.

**Review by markuman — APPROVED** [review]
LGTM

**Comment by markuman** [comment]
This shoud be merge before next release. Because it fixes more than the known issue.   
With the current release (_1.5.0_) the entire  `linuxParameter.capabilities` is not useable (_worked with 2.9.12_).

```yml
        containers:
          - name: mein-lekker
            linuxParameters:
              capabilities:
                add:
                  - NET_BIND_SERVICE
```

Currently it results in 

`line 806, in main\nAttributeError: 'str' object has no attribute 'get'\n"`

This PR fixes also this case.

Maybe the integrationtest should also include something like

```yml
ecs_task_containers_with_linux_parameters:
- name: "{{ ecs_task_name }}"
  image: "{{ ecs_task_image_path }}"
  essential: true
  memory: "{{ ecs_task_memory }}"
  linuxParameters:
    capabilities:
      add:
        - NET_BIND_SERVICE
  portMappings:
  - containerPort: "{{ ecs_task_container_port }}"
    hostPort: "{{ ecs_task_host_port|default(0) }}"
  mountPoints: "{{ ecs_task_mount_points|default([]) }}"
```

fyi @alinabuzachis @jillr

File: plugins/modules/ecs_taskdefinition.py [hunk 4]
```diff
@@ -190,7 +192,7 @@
             linuxParameters:
                 description: Linux-specific modifications that are applied to the container, such as Linux kernel capabilities.
                 required: False
-                type: list
+                type: dict
```
Comment (tremble) [inline plugins/modules/ecs_taskdefinition.py:195]: This looks like it's going from a list of dicts to a dict, is this not a breaking change?  (Although I guess we can do this with 2.0.0

Comment (markuman) [reply plugins/modules/ecs_taskdefinition.py:195]: (_Imho_) it never worked as a `list`. I guess it was one of the transformation errors when `elements` where introduced.

**Review by jillr — COMMENTED** [review]
@alinabuzachis This lgtm, could you please add a changelog? As tremble noted we should call out that `linuxParameters` requires a dict (and that `list` was a bug that never worked)

**Review by markuman — APPROVED** [review]
LGTM
